name: Test Action

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Check executables
        run: |
          Get-Command mxmlc
          Get-Command compc
          Get-Command adt

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Check executables
        run: |
          which mxmlc
          which compc
          which adt

  windows-air-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          air-version: "32.0"
      - name: Check executables
        run: |
          Get-Command mxmlc
          Get-Command compc
          Get-Command adt

  macos-air-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          air-version: "32.0"
      - name: Check executables
        run: |
          which mxmlc
          which compc
          which adt
