on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Check executables
        run: |
          mxmlc -version
          compc -version
          adt -version

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Check executables
        run: |
          mxmlc -version
          compc -version
          adt -version

  air-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          air-version: "32.0"
      - name: Check executables
        run: |
          mxmlc -version
          compc -version
          adt -version
